import os

NOTE_NUM = 2
IMAGE_TYPES = ["jpg", "png", "gif", "webp", "svg"]

def get_images(directory):
    files = os.listdir(directory)
    images = []
    for file in files:
        for image_type in IMAGE_TYPES:
            if file.endswith("." + image_type):
                images.append(os.path.join(directory, file))
    return images

def open_file():
    f = open("Note" + str(NOTE_NUM) + ".jsx", "w", encoding="utf-8")
    return f

def main():
    images = get_images(r'C:\Users\jav3fh\Programming\personal-site\src\notes\0')
    f = open_file()
    f.write("""//Auto-generated by note-generator program
import notes_list from "../notes_list";
import { Link } from "react-router-dom";
import './../notes_page.css';\n""")
    f.write("export default function Note{num}() {{\n".format(num=NOTE_NUM))
    f.write("    const noteIndex = {num};".format(num=NOTE_NUM))
    f.write("""
    const note = notes_list[noteIndex];
    if (!note) return <div className="note-container">Note not found.</div>;
    const prevNote = notes_list[noteIndex + 1];
    const nextNote = notes_list[noteIndex - 1];
    
    return (
    <div className="note-container">
        <Link to="/notes" className="back-link">← Back to Notes</Link>
        <img src={note.image} alt={note.title} className="note-header-image" />
        <h1>{note.title}</h1>
        <div className="note-date">Published on {note.date}</div>\n""")

    r = open("test.md", "r", encoding="utf-8")
    raw = r.read().split("\n")
    raw.pop(0) # remove header
    for line in raw:
        if len(line) < 1:
            continue
        match line[0]:
            case "#":
                f.write("        <h2>" + line[2:] + "</h2>\n")
            case _:
                if line[0] == "\t":
                    line = line[1:]
                f.write("        <p>" + line.strip() + "</p>\n")

    f.write("""
        <div className="note-nav">
            {prevNote && <Link to={prevNote.link} className="note-nav-link">← {prevNote.title}</Link>}
            {nextNote && <Link to={nextNote.link} className="note-nav-link">{nextNote.title} →</Link>}
        </div>
    </div>
    );
}\n""")
    f.close()
    r.close()

if __name__ == "__main__":
    main()
